osx_image: xcode8.3
language: objective-c
xcode_workspace: FirebaseUI.xcworkspace
xcode_scheme: FirebaseUI
cache:
  - bundler
  - cocoapods

rvm: 2.3.1
before_install:
  - open -a "simulator" --args -CurrentDeviceUDID 1FC0DC01-6B14-4A81-9F05-E337EEDC11B2
  - bundle install
  - gem install xcpretty
  - bundle exec pod install --repo-update

script: ./test.sh
