osx_image: xcode7.3
language: objective-c
xcode_workspace: FirebaseUI.xcworkspace
xcode_scheme: FirebaseUI

rvm: 2.3.1
before_install:
  - gem install cocoapods -v '1.0.1'

script: xcodebuild -workspace FirebaseUI.xcworkspace
  -scheme FirebaseUI
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6s'
  test
  ONLY_ACTIVE_ARCH=YES
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
